[project]
authors = ["MarkHaoxiang <mark.haoxiang@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "diffusion-co-design"
platforms = ["linux-64"]
version = "0.1.0"
preview = ["pixi-build"]

[tasks]

[dependencies]
rware = { path = "packages/robotic-warehouse" }
python = "3.12.*"
ipykernel = ">=6.29.5,<7"
hatchling = ">=1.27.0,<2"
pettingzoo = ">=1.24.3,<2"
pydantic = ">=2.10.4,<3"
matplotlib = ">=3.10.0,<4"
numpy = ">=2.2.0,<3"
pydantic-settings = ">=2.7.0,<3"
pillow = ">=11.0.0,<12"
tqdm = ">=4.67.1,<5"

[pypi-dependencies]
torch = "*"
torchrl = "*"
