[project]
authors = ["MarkHaoxiang <mark.haoxiang@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "diffusion-co-design"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
