[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
dependencies = [
    "ipykernel",
    "pettingzoo>=1.24.3,<2",
    "numpy>=2.2.0,<3",
    "pydantic>=2.10.4,<3",
    "pillow>=11.0.0,<12",
    "tqdm>=4.67.1,<5",
    "matplotlib>=3.10.0,<4",
    "pyglet<2",
    "hydra-core>=1.3.2,<2",
    "torch",
    "torchrl",
]
authors = [{ name = "Hao Xiang Li", email = "mark.haoxiang@gmail.com" }]
name = "diffusion-co-design"
requires-python = ">= 3.11"
version = "0.1.0"

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]
preview = ["pixi-build"]

[tool.pixi.package]
name = "diffusion-co-design"
version = "0.1.0"

[tool.pixi.build-system]
build-backend = { name = "pixi-build-python", version = "*" }
channels = ["pixi-build-backends", "conda-forge"]

[tool.pixi.dependencies]
rware = { path = "packages/robotic-warehouse" }
diffusion-co-design = { path = "." }

[tool.pixi.host-dependencies]
hatchling = "==1.26.3"
