[project]
name = "guided_diffusion"
version = "0.1.0"
description = "Taken from https://github.com/rllab-snu/ADD"
authors = [{name = "Tim de Jager", email = "tim@prefix.dev"}]
requires-python = ">= 3.11"
dependencies = ["torch"]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.package]
name = "guided_diffusion"
version = "0.1.0"

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]
preview = ["pixi-build"]

[tool.pixi.build-system]
build-backend = { name = "pixi-build-python", version = "*" }
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]

[tool.pixi.host-dependencies]
hatchling = "==1.26.3"

[tool.pixi.pypi-dependencies]
guided_diffusion = { path = "." , editable = true}

[tool.pixi.dependencies]
pillow = ">=11.1.0,<12"
numpy = ">=2.2.1,<3"
blobfile = ">=3.0.0,<4"



