[project]
name = "guided-diffusion"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "blobfile>=3.0.0",
    "mpi4py>=4.0.2",
    "numpy>=2.2.2",
    "pillow>=10.4.0",
    "torch>=2.6.0",
]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]
